language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-text --configuration resources/phpunit.xml

notifications:
  irc: "irc.freenode.org#fuelphp"